name: MammaMia
options:
  bundleIdPrefix: com.mamamia
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: "15.0"

targets:
  MammaMia:
    type: application
    platform: iOS
    sources:
      - MammaMia
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mamamia.app
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: MammaMia
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "MammaMia needs your location to show you nearby chefs and calculate distances."
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        ENABLE_MODULE_VERIFIER: YES
        SWIFT_STRICT_CONCURRENCY: complete
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
        CLANG_ANALYZER_NONNULL: YES
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
        CLANG_CXX_LANGUAGE_STANDARD: gnu++20
        CLANG_ENABLE_OBJC_WEAK: YES
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
        CLANG_WARN_DOCUMENTATION_COMMENTS: YES
        CLANG_WARN_EMPTY_BODY: YES
        CLANG_WARN_BOOL_CONVERSION: YES
        CLANG_WARN_CONSTANT_CONVERSION: YES
        CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
        CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
        CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
        CLANG_WARN_STRICT_PROTOTYPES: YES
        CLANG_WARN_SUSPICIOUS_MOVE: YES
        CLANG_WARN_UNREACHABLE_CODE: YES
        CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
        GCC_WARN_64_TO_32_BIT_CONVERSION: YES
        GCC_WARN_UNDECLARED_SELECTOR: YES
        GCC_WARN_UNUSED_FUNCTION: YES
        GCC_WARN_UNUSED_VARIABLE: YES 